import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Mono, Poppins } from 'next/font/google'

const roboto = Roboto ({
    subsets: ['latin'],
    weight: ['100', '400', '700'],
    variable: '--font-roboto',
})

const roboto_mono = Roboto_Mono ({
    subsets: ['latin'],
    weight: ['100', '400', '700'],
    variable: '--font-roboto-mono',
})

const poppins = Poppins ({
    subsets: ['latin'],
    weight: ['100', '400', '700'],
    variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-slate-500 m-0">
      <body className={`${roboto.variable} ${roboto_mono.variable} ${poppins.variable}`}>{children}</body>
    </html>
  )
}
